import 'dotenv/config'

export const env = {
  MONGODB_CONNECTION_STRING: process.env.MONGODB_CONNECTION_STRING,
  PORT: process.env.PORT,

  OPENAI_API_KEY: process.env.OPENAI_API_KEY,

  APP_DOMAIN_CDN_IMAGE: process.env.APP_DOMAIN_CDN_IMAGE,

  ACCESS_TOKEN_SECRET_SIGNATURE: process.env.ACCESS_TOKEN_SECRET_SIGNATURE,
  REFRESH_TOKEN_SECRET_SIGNATURE: process.env.REFRESH_TOKEN_SECRET_SIGNATURE,
}